name: "Create Release"
on:
  push:
    paths:
      - '**.mcmeta'
      - 'data/**'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: datapack-v${{ github.run_number }}
          exclusions: '*.git*'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: datapack-v${{ github.run_number }}
          draft: false
          prerelease: false
          files: datapack-v${{ github.run_number }}.zip

